{
 "title": "DD-WRT Router Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Temp",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cputemp",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "cpu" }
     ],
     "target": "ddwrt.perf.temp.cpu.degrees"
    }
   ]
  },
  {
   "title": "CPU Load (1 min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpuload",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "load_one" }
     ],
     "target": "ddwrt.perf.load.load_one.number"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "kbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "free" }
     ],
     "target": "ddwrt.perf.mem.free.kilobytes"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stat", "operator": "=", "value": "user" },
      { "condition": "OR", "key": "stat", "operator": "=", "value": "system" },
      { "condition": "OR", "key": "stat", "operator": "=", "value": "softirq" }
     ],
     "target": "scaleToSeconds(derivative(sumSeries(ddwrt.perf.cpu.{guest,iowait,nice,guest,guest_nice,user,system,irq,softirq})), 1)"
    }
   ]
  },
  {
   "title": "Wireless Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "clients",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "sumSeries(ddwrt.perf.wireless.*.clients)"
    }
   ]
  },
  {
   "title": "Ping latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "latency" }
     ],
     "target": "aliasByNode(ddwrt.perf.ping.*.latency, 3)"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packetloss" }
     ],
     "target": "aliasByNode(ddwrt.perf.ping.*.packetloss.percent, 3)"
    }
   ]
  },
  {
   "title": "Active IP Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_protocol",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "protocol" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "protocol", "operator": "!=", "value": "all" }
     ],
     "target": "aliasByNode(ddwrt.perf.connections.*.number, 3)"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_source",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cputemp",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wireless Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(ddwrt.perf.wireless.*.clients, 3, 4)"
    }
   ]
  },
  {
   "title": "WAN (eth0) Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "direction" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "bandwidth",
     "query": "SELECT derivative(mean(\"bytes\"), $__interval) FROM \"bandwidth\" WHERE (\"interface\" = 'eth0') AND $timeFilter GROUP BY time($__interval), \"direction\" fill(linear)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$__interval" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth1" }
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(ddwrt.perf.network.eth1.receive.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "Bridge (br0) Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(\"bytes\"), $__interval) FROM \"bandwidth\" WHERE (\"interface\" = 'br0') AND $timeFilter GROUP BY time($__interval), \"direction\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(ddwrt.perf.network.br0.receive.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "LAN (eth1)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(\"bytes\"), $__interval) FROM \"bandwidth\" WHERE (\"interface\" = 'eth1') AND $timeFilter GROUP BY time($__interval), \"direction\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(ddwrt.perf.network.eth0.receive.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "Wireless 5GHz (ath0) Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(\"bytes\"), $__interval) FROM \"bandwidth\" WHERE (\"interface\" = 'ath0') AND $timeFilter GROUP BY time($__interval), \"direction\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(ddwrt.perf.network.eth0.receive.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "Wireless 2.4GHz (ath1) Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(\"bytes\"), $__interval) FROM \"bandwidth\" WHERE (\"interface\" = 'ath1') AND $timeFilter GROUP BY time($__interval), \"direction\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(ddwrt.perf.network.ath1.receive.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "VPN Tunnel (tun1) Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(derivative(ddwrt.perf.network.tun1.receive.bytes), 1), 4)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(derivative(ddwrt.perf.network.tun1.transmit.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpuload",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "load_one" },
      { "condition": "OR", "key": "type", "operator": "=", "value": "load_five" },
      { "condition": "OR", "key": "type", "operator": "=", "value": "load_fifteen" }
     ],
     "target": "aliasByNode(ddwrt.perf.load.load_one.number, 3)"
    }
   ]
  },
  {
   "title": "Run Queue (tasks)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "proc_total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpuload",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "proc_total" }
     ],
     "target": "aliasByNode(ddwrt.perf.load.proc_run.number, 3)"
    },
    {
     "alias": "proc_run",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpuload",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "proc_run" }
     ],
     "target": "aliasByNode(ddwrt.perf.load.proc_total.number, 3)"
    }
   ]
  },
  {
   "title": "Memory Total / Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "total" }
     ],
     "target": "aliasByNode(ddwrt.perf.mem.total.kilobytes, 3)"
    },
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "active" },
      { "condition": "OR", "key": "type", "operator": "=", "value": "buffers" },
      { "condition": "OR", "key": "type", "operator": "=", "value": "cached" },
      { "condition": "OR", "key": "type", "operator": "=", "value": "inactive" }
     ],
     "target": "aliasByNode(scale(ddwrt.perf.mem.used.bytes, 0.0010), 3)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_stat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "stat" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stat", "operator": "=", "value": "user" },
      { "condition": "OR", "key": "stat", "operator": "=", "value": "system" },
      { "condition": "OR", "key": "stat", "operator": "=", "value": "softirq" }
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(ddwrt.perf.cpu.*), 1), 3)"
    }
   ]
  }
 ]
}